// Generated by https://quicktype.io

export interface AdminTasksResponse {
   tasks: Task[];
   users: User[];
}

export interface Task {
   id:          number;
   title:       string;
   description: string;
   user_id:     number;
   status:      number;
   created_at:  string;
   updated_at:  string;
   user:        User;
}

export interface User {
   id:                number;
   name:              string;
   email:             string;
   email_verified_at: string;
   created_at:        string;
   updated_at:        string;
   role_id:           number;
   status:            number;
   setPassword:       number;
}
